<a href="https://colab.research.google.com/github/hemangikariya/ML-Lab-Assignments/blob/main/Assignment-2/25MCA30048_Hemangi_PythonAssignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Q-1. Import NumPy and display its version number.**

In [1]:
#import numpy
import numpy as np

# Display version
print("NumPy Version:", np.__version__)

NumPy Version: 2.0.2


# **Q2. Create and display the following arrays:**

a. A one-dimensional array containing numbers from 1 to 10.

In [2]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


b. An array containing only even numbers between 2 and 20.

In [3]:
even = np.arange(2, 21, 2)
print(even)

[ 2  4  6  8 10 12 14 16 18 20]


c. A 5 × 5 array filled with zeros.

In [4]:
zeros = np.zeros((5, 5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


d. A 4 × 4 array filled with ones.

In [5]:
ones = np.ones((4, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# **Q3. Create a 3 × 3 identity matrix.**

In [6]:
# 3 * 3 matrix
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# **Q4. Create a 1D array containing 15 equally spaced values between 0 and 1.**

In [7]:
arr = np.linspace(0, 1, 15)
print(arr)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


# **Q5. Create the following matrix: 10*10 matrix with equally spaced elements between 0 and 1**

In [8]:
matrix = np.linspace(0, 1, 100).reshape(10, 10)
print(matrix)

[[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
  0.06060606 0.07070707 0.08080808 0.09090909]
 [0.1010101  0.11111111 0.12121212 0.13131313 0.14141414 0.15151515
  0.16161616 0.17171717 0.18181818 0.19191919]
 [0.2020202  0.21212121 0.22222222 0.23232323 0.24242424 0.25252525
  0.26262626 0.27272727 0.28282828 0.29292929]
 [0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
  0.36363636 0.37373737 0.38383838 0.39393939]
 [0.4040404  0.41414141 0.42424242 0.43434343 0.44444444 0.45454545
  0.46464646 0.47474747 0.48484848 0.49494949]
 [0.50505051 0.51515152 0.52525253 0.53535354 0.54545455 0.55555556
  0.56565657 0.57575758 0.58585859 0.5959596 ]
 [0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
  0.66666667 0.67676768 0.68686869 0.6969697 ]
 [0.70707071 0.71717172 0.72727273 0.73737374 0.74747475 0.75757576
  0.76767677 0.77777778 0.78787879 0.7979798 ]
 [0.80808081 0.81818182 0.82828283 0.83838384 0.84848485 0.85858586
  0.86868687

# **Q6. Reshape the following array into a 4 × 5 matrix:**

In [9]:
arr = np.arange(1, 21)
matrix = arr.reshape(4, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# **Q7. Generate:**

a. A 3 × 3 matrix of random numbers between 0 and 1.

In [10]:
matrix = np.random.rand(3, 3)
print(matrix)

[[0.79580517 0.54428536 0.73442401]
 [0.75457368 0.03423116 0.75592034]
 [0.62414467 0.90951197 0.84010675]]


b. A 4 × 4 matrix of random integers between 10 and 50.

In [11]:
matrix = np.random.randint(10, 51,(4, 4))
print(matrix)

[[38 35 13 25]
 [16 49 49 10]
 [13 14 20 40]
 [32 23 26 15]]


# **Q8. Create the following matrix without typing each element manually:**

In [12]:
#[[10 20 30]
#[40 50 60]
#[70 80 90]]

matrix = np.arange(10,91,10).reshape(3,3)
print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


#**Q9. Based on the below code, Extract the following:**

In [13]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


a. The element 13

In [14]:
print(mat[2,2])

13


b. The last row

In [15]:
print(mat[-1])

[21 22 23 24 25]


c. The third column

In [16]:
print(mat[:,2])

[ 3  8 13 18 23]


d. The submatrix:

In [17]:
#[[ 7 8 9]
#[12 13 14]
#[17 18 19]]
print(mat[1:4,1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


e. The elements:

In [18]:
#[4 9 14 19 24]
print(mat[:,3])

[ 4  9 14 19 24]


# **Q10. Replace all even numbers in mat with 0.**

In [19]:
mat = np.arange(1,26).reshape(5,5)
mat[mat % 2 == 0] = 0
print(mat)

[[ 1  0  3  0  5]
 [ 0  7  0  9  0]
 [11  0 13  0 15]
 [ 0 17  0 19  0]
 [21  0 23  0 25]]


# **Q11. Find the transpose of mat.**

In [20]:
#Use the matrix mat created earlier.
mat = np.arange(1,26).reshape(5,5)
transpose = mat.T
print(transpose)

[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]


# **Q12. Find:**

In [21]:
mat = np.arange(1,26).reshape(5,5)

a. Sum of all elements

In [22]:
print("Sum =", np.sum(mat))

Sum = 325


b. Mean of all elements

In [23]:
print("Mean =", np.mean(mat))

Mean = 13.0


c. Standard deviation

In [24]:
print("Standard Deviation =", np.std(mat))

Standard Deviation = 7.211102550927978


d. Maximum value

In [25]:
print("Maximum =", np.max(mat))

Maximum = 25


e. Minimum value

In [26]:
print("Minimum =", np.min(mat))

Minimum = 1


# **Q13. Calculate:**

In [27]:
mat = np.arange(1,26).reshape(5,5)

a. Row-wise sums

In [28]:
print("Row-wise Sum")
print(np.sum(mat,axis=1))
print()

Row-wise Sum
[ 15  40  65  90 115]



b. Column-wise sums

In [29]:
print("Column-wise Sum")
print(np.sum(mat,axis=0))
print()

Column-wise Sum
[55 60 65 70 75]



c. Row-wise means

In [30]:
print("Row-wise Mean")
print(np.mean(mat,axis=1))
print()

Row-wise Mean
[ 3.  8. 13. 18. 23.]



d. Column-wise means

In [31]:
print("Column-wise Mean")
print(np.mean(mat,axis=0))

Column-wise Mean
[11. 12. 13. 14. 15.]


# **Q14. Find the indices of all elements greater than 20.**

In [32]:
mat = np.arange(1,26).reshape(5,5)
indices = np.argwhere(mat>20)
print(indices)

[[4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]]


# **Q15. Create an 8 × 8 checkerboard pattern using numpy**

In [33]:
#Expected output:
#[[0 1 0 1 0 1 0 1]
#[1 0 1 0 1 0 1 0]
#...
#]
checkerboard = np.zeros((8,8),dtype=int)
checkerboard[1::2,::2] = 1
checkerboard[::2,1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# **Q16. Generate a random array of size 20 and normalize its values between 0 and 1.**

In [34]:
arr = np.random.rand(20)
normalized = (arr-arr.min())/(arr.max()-arr.min())
print("Original Array")
print(arr)
print()
print("Normalized Array")
print(normalized)

Original Array
[0.96329541 0.91632274 0.85005365 0.35395582 0.84653691 0.16830275
 0.03453605 0.25903521 0.98585083 0.14496377 0.11445799 0.96337748
 0.27973029 0.72137042 0.68924039 0.57484351 0.65294915 0.89876155
 0.16095276 0.71950004]

Normalized Array
[0.97629027 0.92691369 0.85725316 0.33576665 0.85355645 0.14061245
 0.         0.2359883  1.         0.11607905 0.08401208 0.97637654
 0.25774248 0.72198434 0.68821    0.56795865 0.65006149 0.90845377
 0.13288631 0.72001823]


# **Q17. Create two 3 × 3 matrices and perform:**

In [35]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

a. Addition

In [36]:
print(A+B)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


b. Subtraction

In [37]:
print(A-B)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


c. Element-wise multiplication

In [38]:
print(A*B)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


d. Matrix multiplication

In [39]:
print(np.matmul(A,B))
#Another methodḍto write is print(A@B)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
